artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: src/stock_agent/components/stock_names.txt
  local_data_file: artifacts/data_ingestion/


data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_validation
  file_name: all_stocks.csv


model_trainer:
  root_dir: artifacts/model_trainer
  data_dir: artifacts/data_transformation/train.csv
  alpha: 0.001
  beta: 0.002
  gamma: 0.99
  max_size: 250
  tau: 0.005
  batch_size: 64
  history_len: 10
  re_train: False
  epochs: 1
  best_score_file: artifacts/model_trainer/best_score.txt

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_dir: artifacts/data_transformation/test.csv
  best_score_file: artifacts/model_trainer/best_score.txt
  history_len: 10
  model: artifacts/model_trainer/actor.h5 
